---------------------------------------
Begin Slurm Prolog: Jun-27-2025 14:04:38
Job ID:    5620810
User ID:   cfilho3
Account:   gts-itaboada3
Job name:  DeepIceRTX
Partition: gpu-rtx6000
QOS:       embers
---------------------------------------

CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:21 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250627-140920.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:21 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250627-140920.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:21 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250627-140920.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:21 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250627-140920.log[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:21 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:21 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:21 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:21 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - features: ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area'][0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - truth: ['energy', 'energy_track', 'energy_cascade', 'position_x', 'position_y', 'position_z', 'azimuth', 'zenith', 'pid', 'elasticity', 'interaction_type', 'interaction_time', 'inelasticity', 'stopped_muon', 'oneweight'][0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:50 - IceMixNodes.__init__ - hlc name 'None' not found in input_feature_names '['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']', subsampling will be random.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - features: ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area'][0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - truth: ['energy', 'energy_track', 'energy_cascade', 'position_x', 'position_y', 'position_z', 'azimuth', 'zenith', 'pid', 'elasticity', 'interaction_type', 'interaction_time', 'inelasticity', 'stopped_muon', 'oneweight'][0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:50 - IceMixNodes.__init__ - hlc name 'None' not found in input_feature_names '['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']', subsampling will be random.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - features: ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area'][0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - truth: ['energy', 'energy_track', 'energy_cascade', 'position_x', 'position_y', 'position_z', 'azimuth', 'zenith', 'pid', 'elasticity', 'interaction_type', 'interaction_time', 'inelasticity', 'stopped_muon', 'oneweight'][0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:50 - IceMixNodes.__init__ - hlc name 'None' not found in input_feature_names '['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']', subsampling will be random.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - features: ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area'][0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - main - truth: ['energy', 'energy_track', 'energy_cascade', 'position_x', 'position_y', 'position_z', 'azimuth', 'zenith', 'pid', 'elasticity', 'interaction_type', 'interaction_time', 'inelasticity', 'stopped_muon', 'oneweight'][0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:50 - IceMixNodes.__init__ - hlc name 'None' not found in input_feature_names '['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']', subsampling will be random.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `val_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `val_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `test_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `test_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `val_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `test_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `val_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:09:50 - _set_dataloader_kwargs - No `test_dataloader_kwargs` given. This arg has been set to `train_dataloader_kwargs` with `shuffle` = False.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:51 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:51 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:51 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:51 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:58 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:58 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:58 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:09:58 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:02 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:02 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:02 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:02 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:05 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:05 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:05 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-27 14:10:05 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time[0m
patience = 6
factor = 0.5
threshold = 0.0001
mode = min
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:10:10 - StandardModel._print_callbacks - Training initiated with callbacks: ModelCheckpoint, ProgressBar, EpochMonitorCallback, CheckSamplerCallback[0m
patience = 6
factor = 0.5
threshold = 0.0001
mode = min
patience = 6
factor = 0.5
threshold = 0.0001
mode = min
patience = 6
factor = 0.5
threshold = 0.0001
mode = min
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:10:10 - StandardModel._print_callbacks - Training initiated with callbacks: ModelCheckpoint, ProgressBar, EpochMonitorCallback, CheckSamplerCallback[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:10:10 - StandardModel._print_callbacks - Training initiated with callbacks: ModelCheckpoint, ProgressBar, EpochMonitorCallback, CheckSamplerCallback[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-27 14:10:10 - StandardModel._print_callbacks - Training initiated with callbacks: ModelCheckpoint, ProgressBar, EpochMonitorCallback, CheckSamplerCallback[0m
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:75: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]` or one of them to enable TensorBoard support by default
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[W CUDAAllocatorConfig.h:30] Warning: expandable_segments not supported on this platform (function operator())
[W CUDAAllocatorConfig.h:30] Warning: expandable_segments not supported on this platform (function operator())
[W CUDAAllocatorConfig.h:30] Warning: expandable_segments not supported on this platform (function operator())
[W CUDAAllocatorConfig.h:30] Warning: expandable_segments not supported on this platform (function operator())
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "train_icemix.py", line 317, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_icemix.py", line 317, in <module>
  File "train_icemix.py", line 317, in <module>
        main(main(

  File "train_icemix.py", line 203, in main
  File "train_icemix.py", line 203, in main
    main(
  File "train_icemix.py", line 203, in main
        model.fit(model.fit(

  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/src/graphnet/models/standard_model.py", line 167, in fit
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/src/graphnet/models/standard_model.py", line 167, in fit
    model.fit(
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/src/graphnet/models/standard_model.py", line 167, in fit
    trainer.fit(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    trainer.fit(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    trainer.fit(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
            call._call_and_handle_interrupt(call._call_and_handle_interrupt(call._call_and_handle_interrupt(


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 46, in _call_and_handle_interrupt
            return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
            return function(*args, **kwargs)return function(*args, **kwargs)return function(*args, **kwargs)


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self._run(model, ckpt_path=ckpt_path)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    self._run(model, ckpt_path=ckpt_path)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 943, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 103, in _call_setup_hook
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 103, in _call_setup_hook
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 103, in _call_setup_hook
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 218, in _call_callback_hooks
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 218, in _call_callback_hooks
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 218, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 175, in setup
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 175, in setup
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 175, in setup
            self.disable()self.disable()self.disable()


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 155, in disable
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 155, in disable
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/callbacks/progress/progress_bar.py", line 155, in disable
    raise NotImplementedError
NotImplementedError
    raise NotImplementedError
    NotImplementedErrorraise NotImplementedError

NotImplementedError
[2025-06-27 14:10:51,672] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 3217180 closing signal SIGTERM
[2025-06-27 14:10:51,986] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 3217181) of binary: /storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/bin/python3.8
Traceback (most recent call last):
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_icemix.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-06-27_14:10:51
  host      : atl1-1-02-004-27-0.pace.gatech.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 3217182)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-06-27_14:10:51
  host      : atl1-1-02-004-27-0.pace.gatech.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 3217183)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-27_14:10:51
  host      : atl1-1-02-004-27-0.pace.gatech.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3217181)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: atl1-1-02-004-27-0: task 0: Exited with exit code 1
---------------------------------------
Begin Slurm Epilog: Jun-27-2025 14:11:29
Job ID:        5620810
User ID:       cfilho3
Account:       gts-itaboada3
Job name:      DeepIceRTX
Resources:     cpu=24,gres/gpu:rtx_6000=4,mem=340G,node=1
Rsrc Used:     cput=02:32:00,vmem=0,walltime=00:06:20,mem=61384K,energy_used=0
Partition:     gpu-rtx6000
QOS:           embers
Nodes:         atl1-1-02-004-27-0
---------------------------------------
